apiVersion: apps/v1beta1
kind: ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http: 
        - path: /
          backend:
            serviceName: client-cluster-ip-servcie
            servicePort: 3000
        - path: /api/
          backend:
            serviceName: server-client-ip-service
            ServicePort: 5000